//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UklonBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UklonBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add 5 uan.
        /// </summary>
        internal static string add_5uan {
            get {
                return ResourceManager.GetString("add_5uan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your comment: .
        /// </summary>
        internal static string add_comment {
            get {
                return ResourceManager.GetString("add_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added 5 uan.
        /// </summary>
        internal static string added_5uan {
            get {
                return ResourceManager.GetString("added_5uan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional details.
        /// </summary>
        internal static string additional_details {
            get {
                return ResourceManager.GetString("additional_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t like music.
        /// </summary>
        internal static string bad_music {
            get {
                return ResourceManager.GetString("bad_music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter number of the building.
        /// </summary>
        internal static string building_number {
            get {
                return ResourceManager.GetString("building_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel creation.
        /// </summary>
        internal static string cancel_creation {
            get {
                return ResourceManager.GetString("cancel_creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel order.
        /// </summary>
        internal static string cancel_order {
            get {
                return ResourceManager.GetString("cancel_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car brand:.
        /// </summary>
        internal static string car_brand {
            get {
                return ResourceManager.GetString("car_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car color: .
        /// </summary>
        internal static string car_color {
            get {
                return ResourceManager.GetString("car_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car info.
        /// </summary>
        internal static string car_info {
            get {
                return ResourceManager.GetString("car_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The car was late.
        /// </summary>
        internal static string car_not_in_time {
            get {
                return ResourceManager.GetString("car_not_in_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change city.
        /// </summary>
        internal static string change_city {
            get {
                return ResourceManager.GetString("change_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city has been changed.
        /// </summary>
        internal static string changed_city {
            get {
                return ResourceManager.GetString("changed_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose city.
        /// </summary>
        internal static string choose_city {
            get {
                return ResourceManager.GetString("choose_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose place.
        /// </summary>
        internal static string choose_place {
            get {
                return ResourceManager.GetString("choose_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose place from list.
        /// </summary>
        internal static string choose_place_from_list {
            get {
                return ResourceManager.GetString("choose_place_from_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the trip you want to report to.
        /// </summary>
        internal static string choose_trip_to_complaint {
            get {
                return ResourceManager.GetString("choose_trip_to_complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what you remember.
        /// </summary>
        internal static string choose_what_you_remember {
            get {
                return ResourceManager.GetString("choose_what_you_remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current order will be canceled, continue?.
        /// </summary>
        internal static string confirm_cancel {
            get {
                return ResourceManager.GetString("confirm_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of the trip.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport was defective.
        /// </summary>
        internal static string defective_transport {
            get {
                return ResourceManager.GetString("defective_transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe what you remember.
        /// </summary>
        internal static string describe_what_you_remember {
            get {
                return ResourceManager.GetString("describe_what_you_remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string destination_address {
            get {
                return ResourceManager.GetString("destination_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver&apos;s name: .
        /// </summary>
        internal static string driver_name {
            get {
                return ResourceManager.GetString("driver_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver&apos;s phone: .
        /// </summary>
        internal static string driver_phone {
            get {
                return ResourceManager.GetString("driver_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra cost.
        /// </summary>
        internal static string extra_cost {
            get {
                return ResourceManager.GetString("extra_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I help you?.
        /// </summary>
        internal static string how_can_i_help_you {
            get {
                return ResourceManager.GetString("how_can_i_help_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask me to order a taxi and provide your details.
        /// </summary>
        internal static string how_to_order_taxi {
            get {
                return ResourceManager.GetString("how_to_order_taxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the address.
        /// </summary>
        internal static string input_address {
            get {
                return ResourceManager.GetString("input_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter confirmation code: .
        /// </summary>
        internal static string input_code {
            get {
                return ResourceManager.GetString("input_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Provide the destination address.
        /// </summary>
        internal static string input_destination {
            get {
                return ResourceManager.GetString("input_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone: .
        /// </summary>
        internal static string input_phone {
            get {
                return ResourceManager.GetString("input_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input number in format 38 ....
        /// </summary>
        internal static string input_phone_hint {
            get {
                return ResourceManager.GetString("input_phone_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver was intrustive.
        /// </summary>
        internal static string intrusive_driver {
            get {
                return ResourceManager.GetString("intrusive_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First you need to register. Right after that you can make an order..
        /// </summary>
        internal static string lets_create_account {
            get {
                return ResourceManager.GetString("lets_create_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, answer a couple of questions for us to be able to help you find your thing.
        /// </summary>
        internal static string loss_sth {
            get {
                return ResourceManager.GetString("loss_sth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, answer a couple of questions for us to be able to help you find your.
        /// </summary>
        internal static string loss_thing {
            get {
                return ResourceManager.GetString("loss_thing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not sure if I understood you correctly. Rephrase your message, please..
        /// </summary>
        internal static string Not_understand {
            get {
                return ResourceManager.GetString("Not_understand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order was canceled.
        /// </summary>
        internal static string order_cancelled {
            get {
                return ResourceManager.GetString("order_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order created successfully.
        /// </summary>
        internal static string order_created {
            get {
                return ResourceManager.GetString("order_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order details.
        /// </summary>
        internal static string order_details {
            get {
                return ResourceManager.GetString("order_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup address.
        /// </summary>
        internal static string pickup_address {
            get {
                return ResourceManager.GetString("pickup_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup time: .
        /// </summary>
        internal static string pickup_time {
            get {
                return ResourceManager.GetString("pickup_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No place found with this number. Please check this.
        /// </summary>
        internal static string place_not_found {
            get {
                return ResourceManager.GetString("place_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No place found. Please check this.
        /// </summary>
        internal static string place_not_found2 {
            get {
                return ResourceManager.GetString("place_not_found2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No street or place with this name was found. Try to clarify..
        /// </summary>
        internal static string place_or_street_not_found {
            get {
                return ResourceManager.GetString("place_or_street_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change details or send?.
        /// </summary>
        internal static string prompt_change_details_or_send {
            get {
                return ResourceManager.GetString("prompt_change_details_or_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to provide the address of the destination, or should we just send the car (taximeter)?.
        /// </summary>
        internal static string prompt_destination {
            get {
                return ResourceManager.GetString("prompt_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What did not you like?.
        /// </summary>
        internal static string prompt_what_was_bad {
            get {
                return ResourceManager.GetString("prompt_what_was_bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate your trip.
        /// </summary>
        internal static string rate_trip {
            get {
                return ResourceManager.GetString("rate_trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Let&apos;s try again..
        /// </summary>
        internal static string registration_fail {
            get {
                return ResourceManager.GetString("registration_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you have successfully registered.
        /// </summary>
        internal static string registration_success {
            get {
                return ResourceManager.GetString("registration_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is accepted. We will contact you..
        /// </summary>
        internal static string request_received {
            get {
                return ResourceManager.GetString("request_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are looking for a car for you....
        /// </summary>
        internal static string searching_car {
            get {
                return ResourceManager.GetString("searching_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request.
        /// </summary>
        internal static string send_request {
            get {
                return ResourceManager.GetString("send_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Send a taxi.
        /// </summary>
        internal static string send_taxi {
            get {
                return ResourceManager.GetString("send_taxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code was sent to the number .
        /// </summary>
        internal static string sent_code {
            get {
                return ResourceManager.GetString("sent_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street or place:.
        /// </summary>
        internal static string street_or_place {
            get {
                return ResourceManager.GetString("street_or_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your review has been accepted. Thank you for using UKLON!.
        /// </summary>
        internal static string thank_you {
            get {
                return ResourceManager.GetString("thank_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you! We will do everything to make your trips comfortable with UKLON..
        /// </summary>
        internal static string thanks_for_complaint {
            get {
                return ResourceManager.GetString("thanks_for_complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you! Maybe, something else?.
        /// </summary>
        internal static string thanks_maybe_sth_else {
            get {
                return ResourceManager.GetString("thanks_maybe_sth_else", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many attempts. Try again..
        /// </summary>
        internal static string too_many_attempts {
            get {
                return ResourceManager.GetString("too_many_attempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uan.
        /// </summary>
        internal static string uan {
            get {
                return ResourceManager.GetString("uan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change address?.
        /// </summary>
        internal static string wanna_change_addreess {
            get {
                return ResourceManager.GetString("wanna_change_addreess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to change anything while we are looking for a car?.
        /// </summary>
        internal static string wanna_change_sth {
            get {
                return ResourceManager.GetString("wanna_change_sth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to change?.
        /// </summary>
        internal static string what_to_change {
            get {
                return ResourceManager.GetString("what_to_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
