//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UklonBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UklonBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the address.
        /// </summary>
        internal static string input_address {
            get {
                return ResourceManager.GetString("input_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Provide the destination address.
        /// </summary>
        internal static string input_destination {
            get {
                return ResourceManager.GetString("input_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, answer a couple of questions for us to be able to help you find your thing.
        /// </summary>
        internal static string loss_sth {
            get {
                return ResourceManager.GetString("loss_sth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, answer a couple of questions for us to be able to help you find your.
        /// </summary>
        internal static string loss_thing {
            get {
                return ResourceManager.GetString("loss_thing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not sure if I understood you correctly. Rephrase your message, please..
        /// </summary>
        internal static string Not_understand {
            get {
                return ResourceManager.GetString("Not_understand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No place found with this number. Please check this.
        /// </summary>
        internal static string place_not_found {
            get {
                return ResourceManager.GetString("place_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No place found. Please check this.
        /// </summary>
        internal static string place_not_found2 {
            get {
                return ResourceManager.GetString("place_not_found2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to provide the address of the destination, or should we just send the car (taximeter)?.
        /// </summary>
        internal static string prompt_destination {
            get {
                return ResourceManager.GetString("prompt_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Let&apos;s try again..
        /// </summary>
        internal static string registration_fail {
            get {
                return ResourceManager.GetString("registration_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you have successfully registered.
        /// </summary>
        internal static string registration_success {
            get {
                return ResourceManager.GetString("registration_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are looking for a car for you....
        /// </summary>
        internal static string searching_car {
            get {
                return ResourceManager.GetString("searching_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Send a taxi.
        /// </summary>
        internal static string send_taxi {
            get {
                return ResourceManager.GetString("send_taxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your review has been accepted. Thank you for using UKLON!.
        /// </summary>
        internal static string thank_you {
            get {
                return ResourceManager.GetString("thank_you", resourceCulture);
            }
        }
    }
}
